from __future__ import annotations

import uuid
from datetime import datetime, timedelta
from typing import Any


def build_news_fixtures(now: datetime | None = None) -> list[dict[str, Any]]:
    base_now = now or datetime.utcnow()

    def first_sentence(text: str) -> str:
        stripped = text.strip()
        for separator in (".", "!", "?"):
            index = stripped.find(separator)
            if index != -1:
                return stripped[: index + 1]
        return stripped[:180]

    def make_item(
        *,
        title: str,
        title_ru: str,
        title_kz: str,
        content: str,
        content_ru: str,
        content_kz: str,
        category: str,
        types: list[str],
        summary: str,
        location: str,
        created_hours_ago: int,
        start_offset_hours: int | None = None,
        end_offset_hours: int | None = None,
    ) -> dict[str, Any]:
        start_at = base_now + timedelta(hours=start_offset_hours) if start_offset_hours is not None else None
        end_at = base_now + timedelta(hours=end_offset_hours) if end_offset_hours is not None else None
        created_at = base_now - timedelta(hours=created_hours_ago)
        return {
            "id": str(uuid.uuid4()),
            "title": title_ru,
            "title_ru": title_ru,
            "title_kz": title_kz,
            "title_en": title,
            "content": content_ru,
            "content_ru": content_ru,
            "content_kz": content_kz,
            "content_en": content,
            "summary": summary,
            "summary_ru": summary,
            "summary_kz": first_sentence(content_kz),
            "summary_en": first_sentence(content),
            "source_lang": "ru",
            "translation_status": "translated",
            "category": category,
            "types": types,
            "location": location,
            "image": None,
            "start_at": start_at,
            "end_at": end_at,
            "created_at": created_at,
            "updated_at": created_at,
            "is_active": True,
        }

    return [
        make_item(
            title="Emergency water shutdown near Abai Avenue",
            title_ru="Аварийное отключение воды на проспекте Абая",
            title_kz="Абай даңғылы маңында судың апаттық өшуі",
            content="Emergency crews are fixing a burst pipe. Water supply is limited while restoration teams work on the damaged section.",
            content_ru="Аварийные бригады устраняют прорыв трубы. На время работ подача воды ограничена на ближайших улицах.",
            content_kz="Апаттық бригадалар құбыр жарылуын қалпына келтіруде. Жөндеу кезінде жақын көшелерде су беру шектеледі.",
            category="Коммунальные услуги",
            types=["Аварийные работы", "Плановые работы"],
            summary="Временное ограничение воды из-за аварии на сетях.",
            location="пр. Абая, квартал 40",
            created_hours_ago=2,
            start_offset_hours=-1,
            end_offset_hours=5,
        ),
        make_item(
            title="Ice cleanup planned at bus platforms",
            title_ru="Плановая очистка льда на автобусных остановках",
            title_kz="Автобус аялдамаларында мұзды жоспарлы тазалау",
            content="Municipal teams will clean ice and apply anti-slip materials at key transport hubs.",
            content_ru="Коммунальные службы очистят лёд и обработают противоскользящими материалами крупные остановочные узлы.",
            content_kz="Коммуналдық қызметтер ірі аялдама тораптарында мұзды тазалап, тайғанауға қарсы материалдар себеді.",
            category="Транспорт",
            types=["Плановые работы", "Погодные условия"],
            summary="Подготовка остановок к вечернему пассажиропотоку.",
            location="Станции по пр. Туран",
            created_hours_ago=6,
            start_offset_hours=4,
            end_offset_hours=11,
        ),
        make_item(
            title="Classes switch online because of strong wind",
            title_ru="Занятия переводятся в онлайн из-за сильного ветра",
            title_kz="Қатты желге байланысты сабақтар онлайнға ауыстырылады",
            content="Several schools are moving afternoon classes online while the wind warning remains active.",
            content_ru="Несколько школ переводят дневные занятия в онлайн, пока действует штормовое предупреждение по ветру.",
            content_kz="Қатты жел туралы ескерту сақталған кезде бірнеше мектеп түстен кейінгі сабақты онлайн форматқа ауыстырады.",
            category="Образование",
            types=["Управление образования", "Погодные условия"],
            summary="Часть школ города меняет формат занятий.",
            location="Школы районов Алматы и Есиль",
            created_hours_ago=1,
            start_offset_hours=-2,
            end_offset_hours=8,
        ),
        make_item(
            title="Republic Avenue lane repair starts tomorrow",
            title_ru="Завтра начнётся ремонт полосы на проспекте Республики",
            title_kz="Ертең Республика даңғылында жолақ жөндеуі басталады",
            content="Traffic will be partially restricted while one lane is resurfaced and signage is updated.",
            content_ru="Движение будет частично ограничено: одну полосу закроют на обновление покрытия и дорожных знаков.",
            content_kz="Қаптаманы жаңарту және белгілерді ауыстыру үшін қозғалыс ішінара шектеледі.",
            category="Дороги",
            types=["Дорожные ситуации"],
            summary="Частичное ограничение движения на завтра.",
            location="пр. Республики, участок у моста",
            created_hours_ago=10,
            start_offset_hours=14,
            end_offset_hours=30,
        ),
        make_item(
            title="Neighborhood cleanup day in city courtyards",
            title_ru="Субботник во дворах жилых кварталов",
            title_kz="Тұрғын квартал аулаларындағы сенбілік",
            content="Residents and district services will clean public spaces, remove dry branches, and repaint small urban furniture.",
            content_ru="Жители вместе с районными службами очистят общественные пространства, уберут сухие ветки и обновят малые формы.",
            content_kz="Тұрғындар мен аудандық қызметтер қоғамдық аумақтарды тазалап, құрғақ бұтақтарды алып, шағын нысандарды жаңартады.",
            category="Благоустройство",
            types=["Мероприятия города"],
            summary="Городской субботник для дворов и скверов.",
            location="Дворы районов Сарыарка и Байконыр",
            created_hours_ago=18,
            start_offset_hours=-20,
            end_offset_hours=-6,
        ),
        make_item(
            title="Storm drainage flushed after heavy rain",
            title_ru="Ливнёвка прочищена после сильного дождя",
            title_kz="Қатты жаңбырдан кейін нөсер жүйесі тазартылды",
            content="Utility teams completed cleaning and reopening storm drains in the most waterlogged streets.",
            content_ru="Коммунальные службы завершили прочистку и открытие ливнёвых решёток на наиболее подтопленных улицах.",
            content_kz="Коммуналдық қызметтер су басқан көшелердегі нөсер торларын тазалап, қайта ашты.",
            category="Коммунальные услуги",
            types=["Погодные условия", "Аварийные работы"],
            summary="Подтопленные участки приведены в рабочее состояние.",
            location="ул. Сейфуллина и прилегающие кварталы",
            created_hours_ago=26,
            start_offset_hours=-28,
            end_offset_hours=-3,
        ),
        make_item(
            title="Bus detour for weekend festival",
            title_ru="Изменение автобусных маршрутов на время городского фестиваля",
            title_kz="Қалалық фестиваль кезінде автобустардың бағыты өзгереді",
            content="Several routes will detour around the central square during the festival and evening concert.",
            content_ru="Несколько маршрутов объедут центральную площадь во время фестиваля и вечернего концерта.",
            content_kz="Фестиваль мен кешкі концерт кезінде бірнеше маршрут орталық алаңды айналып өтеді.",
            category="Транспорт",
            types=["Мероприятия города", "Дорожные ситуации"],
            summary="Маршруты изменятся на время фестиваля в центре.",
            location="Площадь у акимата",
            created_hours_ago=12,
            start_offset_hours=20,
            end_offset_hours=34,
        ),
        make_item(
            title="School canteen maintenance completed",
            title_ru="Плановое обслуживание школьных столовых завершено",
            title_kz="Мектеп асханаларын жоспарлы жөндеу аяқталды",
            content="Maintenance teams finished servicing kitchen equipment in several schools and cafeterias resumed normal operation.",
            content_ru="Специалисты завершили обслуживание оборудования школьных столовых, питание работает в обычном режиме.",
            content_kz="Мектеп асханаларының жабдығына қызмет көрсету аяқталды, тамақтану қалыпты режимге оралды.",
            category="Образование",
            types=["Управление образования", "Плановые работы"],
            summary="Столовые снова работают в обычном режиме.",
            location="Школы района Есиль",
            created_hours_ago=40,
            start_offset_hours=-48,
            end_offset_hours=-12,
        ),
        make_item(
            title="Snow removal intensified on ring roads",
            title_ru="Усилена уборка снега на кольцевых дорогах",
            title_kz="Айналма жолдарда қар тазалау күшейтілді",
            content="Road crews increased snow removal and de-icing on high-speed connectors to keep traffic stable.",
            content_ru="Дорожные службы усилили уборку снега и противогололёдную обработку на скоростных связках города.",
            content_kz="Жол қызметтері қаладағы жылдам магистральдарда қар тазалау мен көктайғаққа қарсы өңдеуді күшейтті.",
            category="Дороги",
            types=["Погодные условия", "Дорожные ситуации"],
            summary="Дополнительная техника работает на магистралях.",
            location="Кольцевая дорога и подъезды к мостам",
            created_hours_ago=3,
            start_offset_hours=-5,
            end_offset_hours=7,
        ),
        make_item(
            title="Park lighting modernization project announced",
            title_ru="Объявлен проект модернизации освещения в парках",
            title_kz="Саябақ жарығын жаңарту жобасы жарияланды",
            content="The city is preparing to replace older lighting poles in recreational areas with new energy-efficient fixtures.",
            content_ru="Город готовит замену устаревших опор освещения в парках на новые энергоэффективные светильники.",
            content_kz="Қала демалыс аймақтарындағы ескі жарық бағандарын жаңа үнемді шамдарға ауыстыруды жоспарлап отыр.",
            category="Благоустройство",
            types=["Плановые работы"],
            summary="Подготовка к обновлению освещения в зонах отдыха.",
            location="Парк Жерұйык и скверы центра",
            created_hours_ago=30,
            start_offset_hours=36,
            end_offset_hours=72,
        ),
        make_item(
            title="Warm weather opens additional cycling lanes",
            title_ru="Из-за потепления открываются дополнительные велополосы",
            title_kz="Күннің жылынуына байланысты қосымша веложолақтар ашылады",
            content="Temporary cycling corridors are being opened earlier this season in response to stable weather.",
            content_ru="Временные велокоридоры открываются раньше обычного благодаря устойчивой тёплой погоде.",
            content_kz="Тұрақты жылы ауа райына байланысты уақытша велодәліздер маусымнан ертерек ашылады.",
            category="Погода",
            types=["Погодные условия", "Мероприятия города"],
            summary="Город открывает весенние маршруты раньше срока.",
            location="Набережная Есиля",
            created_hours_ago=22,
            start_offset_hours=10,
            end_offset_hours=60,
        ),
        make_item(
            title="Emergency heating restoration in residential block",
            title_ru="В жилом квартале восстановлено аварийное отопление",
            title_kz="Тұрғын кварталда апаттық жылу қалпына келтірілді",
            content="Heating engineers restored circulation after replacing a damaged valve in the basement node.",
            content_ru="Инженеры восстановили циркуляцию отопления после замены повреждённого клапана в тепловом узле.",
            content_kz="Инженерлер жертөледегі зақымдалған клапанды ауыстырғаннан кейін жылу айналымын қалпына келтірді.",
            category="Коммунальные услуги",
            types=["Аварийные работы"],
            summary="Подача тепла в дома возвращена после аварийных работ.",
            location="ЖК на ул. Кошкарбаева",
            created_hours_ago=16,
            start_offset_hours=-18,
            end_offset_hours=-2,
        ),
        make_item(
            title="Public transport shelters to be renovated",
            title_ru="Остановочные павильоны готовят к обновлению",
            title_kz="Аялдама павильондары жаңартуға дайындалады",
            content="Transit shelters in the busiest corridors will receive new glazing, benches, and route signs.",
            content_ru="Павильоны на загруженных маршрутах получат новое остекление, скамейки и маршрутные схемы.",
            content_kz="Жолаушылар көп жүретін бағыттардағы павильондар жаңа әйнекпен, орындықтармен және сызбалармен жабдықталады.",
            category="Транспорт",
            types=["Плановые работы"],
            summary="Обновление павильонов на магистральных маршрутах.",
            location="Остановки пр. Кабанбай батыра",
            created_hours_ago=48,
            start_offset_hours=30,
            end_offset_hours=96,
        ),
        make_item(
            title="School olympiad finals begin this week",
            title_ru="Финал городской олимпиады школьников стартует на неделе",
            title_kz="Қалалық олимпиаданың финалы осы аптада басталады",
            content="Final rounds for city school olympiads will take place in several academic centers across Astana.",
            content_ru="Финальные туры городской олимпиады школьников пройдут в нескольких учебных центрах Астаны.",
            content_kz="Қалалық олимпиаданың финалдық кезеңдері Астананың бірнеше оқу орталығында өтеді.",
            category="Образование",
            types=["Управление образования", "Мероприятия города"],
            summary="Школьники выходят на финальный этап городской олимпиады.",
            location="Дворец школьников и лицеи города",
            created_hours_ago=8,
            start_offset_hours=26,
            end_offset_hours=54,
        ),
        make_item(
            title="Road markings refreshed after winter wear",
            title_ru="После зимы обновляют дорожную разметку",
            title_kz="Қыстан кейін жол таңбалары жаңартылуда",
            content="Crews are restoring lane markings and pedestrian crossings on streets with heavy traffic.",
            content_ru="Бригады обновляют дорожную разметку и пешеходные переходы на улицах с интенсивным движением.",
            content_kz="Бригадалар көлік ағыны көп көшелердегі жолақтар мен жаяу жүргінші өткелдерін жаңартып жатыр.",
            category="Дороги",
            types=["Плановые работы", "Дорожные ситуации"],
            summary="Весеннее обновление разметки на магистралях.",
            location="ул. Сарайшык и ул. Сыганак",
            created_hours_ago=14,
            start_offset_hours=-3,
            end_offset_hours=18,
        ),
        make_item(
            title="Weekend tree planting campaign announced",
            title_ru="Объявлена акция по высадке деревьев в выходные",
            title_kz="Демалыста ағаш отырғызу акциясы өтеді",
            content="Volunteers and district services will plant new trees and shrubs in public courtyards and alleys.",
            content_ru="Волонтёры и районные службы высадят новые деревья и кустарники во дворах и аллеях города.",
            content_kz="Еріктілер мен аудандық қызметтер аулалар мен аллеяларға жаңа ағаштар мен бұталар егеді.",
            category="Благоустройство",
            types=["Мероприятия города"],
            summary="Подготовка к зелёной акции во дворах и скверах.",
            location="Скверы и дворы района Байконыр",
            created_hours_ago=20,
            start_offset_hours=42,
            end_offset_hours=70,
        ),
        make_item(
            title="Strong frost warning for early morning commuters",
            title_ru="Предупреждение о сильном морозе для утренних пассажиров",
            title_kz="Таңертеңгі жолаушыларға қатты аяз туралы ескерту",
            content="City services advise commuters to dress warmly and expect longer boarding times while vehicles warm up.",
            content_ru="Городские службы рекомендуют пассажирам теплее одеваться и учитывать увеличение времени посадки утром.",
            content_kz="Қалалық қызметтер жолаушыларға жылы киінуді және таңертеңгі отырғызу уақытының ұзаруын ескеруді ұсынады.",
            category="Погода",
            types=["Погодные условия"],
            summary="Рекомендации для жителей на время сильного похолодания.",
            location="Весь город",
            created_hours_ago=4,
            start_offset_hours=-1,
            end_offset_hours=9,
        ),
        make_item(
            title="Suburban route timetable adjusted after repairs",
            title_ru="После ремонта скорректировано расписание пригородных маршрутов",
            title_kz="Жөндеуден кейін қала маңы маршруттарының кестесі өзгертілді",
            content="Route departures were adjusted after maintenance work at the suburban terminal.",
            content_ru="После завершения работ на пригородном терминале скорректировано время отправления маршрутов.",
            content_kz="Қала маңы терминалындағы жұмыстардан кейін маршруттардың жүру уақыты жаңартылды.",
            category="Транспорт",
            types=["Плановые работы", "Дорожные ситуации"],
            summary="Изменения вступают в силу уже сегодня вечером.",
            location="Пригородный терминал Сапаржай",
            created_hours_ago=28,
            start_offset_hours=-32,
            end_offset_hours=-4,
        ),
        make_item(
            title="Noon rain alert for school dismissal time",
            title_ru="Дождевой фронт ожидается к окончанию занятий",
            title_kz="Сабақ аяқталатын уақытта жаңбыр күтіледі",
            content="Parents are advised to monitor updates as rainfall may intensify around school dismissal hours.",
            content_ru="Родителям рекомендуют следить за обновлениями: осадки могут усилиться ко времени окончания уроков.",
            content_kz="Ата-аналарға жаңартуларды бақылау ұсынылады, өйткені жауын сабақ аяқталатын уақытқа қарай күшеюі мүмкін.",
            category="Погода",
            types=["Погодные условия", "Управление образования"],
            summary="Возможное усиление дождя ко времени выхода детей из школ.",
            location="Школы по левому берегу",
            created_hours_ago=5,
            start_offset_hours=2,
            end_offset_hours=12,
        ),
        make_item(
            title="Accessible courtyard ramps upgraded",
            title_ru="Во дворах обновили пандусы и спуски",
            title_kz="Аулаларда пандустар мен түсулер жаңартылды",
            content="Improvement teams completed accessibility upgrades including ramps, tactile strips, and handrails.",
            content_ru="Службы благоустройства завершили обновление пандусов, тактильных полос и поручней во дворах.",
            content_kz="Абаттандыру қызметтері аулалардағы пандустарды, тактильді жолақтарды және тұтқаларды жаңартуды аяқтады.",
            category="Благоустройство",
            types=["Плановые работы"],
            summary="Завершено повышение доступности дворовой среды.",
            location="Дворы района Нура",
            created_hours_ago=55,
            start_offset_hours=-72,
            end_offset_hours=-10,
        ),
        make_item(
            title="Public lecture series on city schools opens next month",
            title_ru="В следующем месяце стартует цикл лекций о городских школах",
            title_kz="Келесі айда қалалық мектептер туралы дәрістер басталады",
            content="The education department is launching a public lecture series for parents about school programs and enrollment.",
            content_ru="Управление образования запускает цикл открытых лекций для родителей о школьных программах и наборе.",
            content_kz="Білім басқармасы ата-аналарға арналған мектеп бағдарламалары мен қабылдау туралы ашық дәрістер циклін бастайды.",
            category="Образование",
            types=["Управление образования"],
            summary="Открытые встречи для родителей и педагогов.",
            location="Дворец школьников",
            created_hours_ago=33,
            start_offset_hours=90,
            end_offset_hours=120,
        ),
        make_item(
            title="Community bulletin without fixed schedule",
            title_ru="Информационное сообщение без фиксированного периода",
            title_kz="Белгіленген мерзімсіз ақпараттық хабарлама",
            content="City services published an informational bulletin with recommendations and reference contacts for residents.",
            content_ru="Городские службы опубликовали информационный бюллетень с рекомендациями и полезными контактами для жителей.",
            content_kz="Қалалық қызметтер тұрғындарға арналған ұсыныстар мен байланыс нөмірлері бар ақпараттық хабарлама жариялады.",
            category="Коммунальные услуги",
            types=["Мероприятия города"],
            summary="Справочная публикация без временного окна.",
            location="",
            created_hours_ago=15,
        ),
    ]
